// <auto-generated />
namespace BasicConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        
        
        string IMigrationMetadata.Id
        {
            get { return "201605190934534_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1ZzW7jNhC+F+g7EDq1RdbKz6U17F1knaQwuomDKFn0FtDS2CFKkSpJBTaKPlkPfaS+Qof6s0RJsWPEi7YoFlgk5PzPN8MZ5a8//hx9WMWcPIPSTIqxdzI49giIUEZMLMdeahbvvvc+vP/6q9FlFK/I55LuzNIhp9Bj78mYZOj7OnyCmOpBzEIltVyYQShjn0bSPz0+/sE/OfEBRXgoi5DRXSoMiyH7BX+dSBFCYlLKr2UEXBfneBNkUskNjUEnNISx95FqFiKDlhzOk2SQc3jknDOK1gTAFx6hQkhDDdo6fNAQGCXFMkjwgPL7dQJIt6BcQ+HDcEO+qzvHp9Ydf8NYigpTbWT8SoEnZ0V8fJd9ryh7VfwwgpcYabO2XmdRxAByufSIq2g44coS9QV4YNmOiHN5VEECkWP/HZFJyk2qYCwgNYryI3KbzjkLf4L1vfwFxFiknNcNRBPxrnGAR7dKJqDM+g4WhdnTyCN+k893GSu2Gk/u1FSYs1OP3KByOudQ5b8WgMBIBT+CAEUNRLfUGFDCyoAsgi3tji77f6kNAYf145FruvoEYmmexh7+6JErtoKoPCkseBAMyw2ZjEqhw8K61pG/yeaLOb6V2uyRY8v2f477dd0zww+e5LZaW3rb3XRk3NBntsy87pDmkTvg2aV+YkneNbPsP+a3V0rGd5IXSMoOHwOZqtB6L92be6qWYHaD6rnWMmSZ6hpWc7VNBy5FRHptyDNQWo1JQESyBDGIKsfed61odAkrza4Jy71vCjvxXODOxAVwMEDOw7zFT6gOadTOAcYgap4g1kFZsFFuKwyrhwnTLgwmQpZQ3meyw7BjLVmDKtHuzQUkIGwZ9MV8F50lUNt6K/FOgLbFY+TXANNuechjkANUYQC2K0xbRnwxt5ew6uqDOBMUrVAXJemixQoPwNT8whFjg+gGXFpQazLbSHYx58B1mGveNiUUhVm7b1WtG/SXCqgysrKvlbOXSqbGXsTGRX7TkY7GUKVuM+z5+bRXToV+z1g4uqZJgq23NiYWJyTIZ8TJu+D1g1Ocy/BD3TE/VdZWmvAloUtwblE1WnrFlDYX1NA5tY15EsUtsk6g9uCoVFnHYjtZJbpKavtzwdE/0HVUdcF/hd7Fth1kT6aT7zZbNqpTTlXH6zyRPI1Ff1fq585nqjp/ftKWMPIdu1sdqBWhVqtuhnunZOS18wbJyJrB65PRzXaYZBTDT11AcbS7jPKBqAvpezQOnNRWH3JJKu1VP3L6zqjoAdt31lZTyEk8guF5ZpFtCMFaG4gHlmAQ/MonnKG/G4JrKtgCtMnnaw9XxlNn5f3nrJ++1hHfYQf94gsCsxHdugK8cjiv733imarwiapvYrr69k13uf9GrBr702uCtW0nyqxtjXlTnDhXY++3jGVIpj8/5lxHZKawpobkmPy+Z5b2WWPyCe5LbhvNEW6PtWmvdaVnsDjIivLvWEvaQ+H2faN33cjfjrEXzSVmNEdu9xDetYn0LiJdYjtXgwPtKHWfN4PmtrWktckcZhNpv/SIkdo3bMSmZsuNCPtFW0DYQEdFMxULWYLUsagkcZrdNRgaIXTOlWELGhq8DkHr7PPTZ8pTJLmM5xBNxSw1SWrQZYjnvPE9y4L9Jf3ZutW0eTRLsk9Eb+ECmsnQBZiJjynjUWX3VUfP7RFhq6h4jGwujX2UlutK0o0UOwoqwlcV/z3ECUdheiYC+gz72Pag4RMsabguB7Z+IdsT0Qz76ILRpaKxLmRs+O3fZXz7h5n3fwMgORvkyhkAAA=="; }
        }
    }
}
