// <auto-generated />
namespace BasicConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201606171243287_Blog.Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Z227jNhB9L9B/IPTUFlkryb60hr2LrJ0URjdxECWLvgW0NHaIUqRKUoGNRb+sD/2k/kKHulmipNi5bS8oAgQxOfc5M5xx/vz9j9H7dczJPSjNpBh7R4NDj4AIZcTEauylZvnme+/9u6+/Gp1G8Zp8KuneWjrkFHrs3RmTDH1fh3cQUz2IWaiklkszCGXs00j6x4eHP/hHRz6gCA9lETK6SoVhMWQf8ONEihASk1J+LiPgujjHmyCTSi5oDDqhIYy9D1SzEBm05HCSJIOcwyMnnFG0JgC+9AgVQhpq0NbhjYbAKClWQYIHlF9vEkC6JeUaCh+GW/J93Tk8tu74W8ZSVJhqI+NHCjx6W8THd9mfFGWvih9G8BQjbTbW6yyKGEAuVx5xFQ0nXFmivgAPLNsBcS4PKkggcuzPAZmk3KQKxgJSoyg/IJfpgrPwJ9hcy19AjEXKed1ANBHvGgd4dKlkAspsrmBZmD2LPOI3+XyXsWKr8eROzYR5e+yRC1ROFxyq/NcCEBip4EcQoKiB6JIaA0pYGZBFsKXd0WV/l9oQcFg/Hjmn648gVuZu7OGfHjlja4jKk8KCG8Gw3JDJqBQ6LHxY6xR0qFiSQ+XZyuu6Rv4WOQ/i6VJq8wQ8Wbb/8dSv65oZ/jcAypb5bjcdGRf0nq0yrzukeeQKeHap71iSd+gs+7f57ZmS8ZXkBZKyw9tApiq03kv35pqqFZj9oHqitQxZprqG1Vxt04FTEZFeG/IMlFZjEhCRLEEMosqx910rGl3CSrNrwnLvm8KOPBe4czEFDgbISZg/JxOqQxq1c4AxiJoniHVQFmyU2wrD6mHCtAuDiZAllPeZ7DDsWUvWoEq0ezOFBIQtg76Y76OzBGpbbyXeCdCueIz8GmDaLQ95DHKAKgzAdoVpy4inC3sJ664+iPNH0Qp1UZIuWqzwAEzNLxxntohuwKUFtSazjWQXcw5ch7nmbVNCUZi1+1bVukF/qIAqIyv7Wjl7qGRq7EVsXOQ3HeloDFXqtoOln0+W5QTq94ygo3OaJNh6ayNpcUKCfB6dvAkeP6TFuQw/1B2zWmVtpQlfEroC5xZVo6VnTGkzpYYuqG3MkyhukXUCtQdHpco6FtvJKtFVUtu/C47+4bGjqgv+M/Qutu0gezKdfLfZsrWAcqo6XueJ5Gks+rtSP3c+v9X585P9JTRmsbqgxkVb3sh34tDqaK2It1p/M317JTevxRdIbtZcHp/cbrbXSW4xTNUFFEf7yygfnLqQvkfolZPa6msuSaW96m9OHxsVPWX3vt1qMjmJRzA89yyyDSbYaAPxwBIMgl/5hDP0d0twTgVbgjb5vO7hunvsrOv/nNXZ1zrie+zPX3zhYDaiO1eKRw779Z1V3FMV3lH1TUzX377EHtor8Lm75n8j9o397nnBb+5smbWtMXSGE/F67H3OWIZk9vNtznVA5gprdEgOyW87FL/kmpVPmF9yG2qOmE9Y6560TvUMPq+yQv071qb20Lp7H+pdh/K3aOxFC4kZzZHbvSR0bUq9i1KX2M7V5ZV2qLrP20F419rU2rReZ1NqTw6Ikdr3+YhNzVZbEfbbfQFhAx0VzUwsZQlSx6KSxGl252BohNA5UYYtaWjwOgSts6/HPlGeIslpvIBoJuapSVKDLkO84I3v2yzYH9KfrYNNm0fz7HHTL+ECmsnQBZiLDynjUWX3WUfP7RFhq6h4jGwujX2UVptK0oUUewoqwlcV/zXECUdhei4Ceg9Pse1Gw0dY0XBTDoD9QnYnohn20ZTRlaKxLmRs+e3/qHz7T6p3fwG0+f3A1hoAAA=="; }
        }
    }
}
