// <auto-generated />
namespace BasicConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201606171245166_Post.Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1Z227jNhB9L9B/IPTUFlkryT60NexdZO2kCLqJg8hZ9C2gpbFDlCJVkgpsFP2yPvST+gsd6maJkmLntr2gMGBYJOfMcHhmOCP/+fsfo/frmJN7UJpJMfaOBoceARHKiInV2EvN8s133vt3X34xOo3iNflUrntr16Gk0GPvzphk6Ps6vIOY6kHMQiW1XJpBKGOfRtI/Pjz83j868gEhPMQiZHSdCsNiyB7wcSJFCIlJKb+QEXBdjONMkKGSSxqDTmgIY+8D1SxEAS05nCTJIJfwyAlnFK0JgC89QoWQhhq0dXijITBKilWQ4ADl800CuG5JuYZiD8Pt8n23c3hst+NvBUuoMNVGxo8EPHpb+Md3xZ/kZa/yH3rwFD1tNnbXmRfRgVyuPOIqGk64sov6HDywYgfEmTyoKIHMsZ8DMkm5SRWMBaRGUX5ArtIFZ+GPsJnLn0GMRcp53UA0EecaAzh0pWQCymyuYVmYfR55xG/K+a5gJVaTyTd1LszbY49conK64FCdf80BgZEKfgABihqIrqgxoITFgMyDLe2OLvtdakPCYfx45IKuP4JYmbuxhz89csbWEJUjhQU3gmG4oZBRKXRY+LDWKehQsSSnyrOV13WN/C1zHuTTldTmCXyyYv/zqV/XnBn+NxBqosCaWyqe4sMcM/VsudRgHo1mk8ZupzkYl/SerTIfdqB55Bp4NqnvWJLn+4xLt/nsmZLxteQFL7PB20CmKrS+lO7MnKqV3dY+xD/RWoYsU11jfq62uYFTEZFeG/LzLK3GI0V+swQZjSrH3jctb3SBlWbXwPLdN8GOPDcMZmIKHAyQkzC/nCZUhzRqnwH6IGqOYOSAstSl3MYrxiITph1mTIQsobzPZEdgz8i0BlXQ7swUEhA2qPp8vo/OkqhtvRW846Bd/hj5NcK0EyjKGJQAVRiAyQ+PLVs8XdhJWHdlVaxmisSqiwB32WLBAzC1fWFxtGV0gy4tqjWFrSe7hHPiOsK13TYRisCszbei1nX6QwFUGVnZ1zqzh0KmJl74xmV+cyMdiaE6um2Z6ud1alnP+j0F7eiCJgkm8lqBW4yQIK9uJ2+Cx5d8cY7hh7qj8qusrTThvURX4MyiarT0jCltMOfTBbWJeRLFrWWdRO3hUamyzsX2YZXsKlfb34VEfynaEdWF/BnuLrbpILuAnfNui2VNBuVUddz1E8nTWPRnpX7pvBqsy+cj+yM0Krs6UGOijTfyHT+0MlrL463U3zy+vQ43j8UXONwsuTz+cLvFXudwi9KsDlAM7Y9R1Vl1lGpwf5zy4qrD9F1mr0yOVn50l1Taqzzp5MNRkZt2vwVoJat8iUfQPfcssokq2GgD8cAuGAS/8AlnuN/tggsq2BK0ybsID5vwY+clwj+nofe1jvgeXf1nb4OY9ejORueRTUO9kxb3VIV3VH0V0/XXL9Ed9wI+twP+b/i+0XU+z/lOJxnhg33nJ4tO8kpByPK3id8+s6/MPNEqlc+xal+PvV8zkSE5/+k2lzogM4XxPySH5Lcdil+yFcyr4M/ZsTXL4Ce0nk9q+XqKs1dp8/4drV27sN7ds/W2bPk9h+G0kHiiOXO7G5mubq63meuC7WyvXqnPq+95W6zvau1a3eDrdHPtqgQ5UvsHA7mp2WoLYf/PEBA22FGtORdLWZLUsahc4iS7CzAUsyc9UYYtaWhwOgStsxeCnyhPcclpvIDoXMxSk6QGtwzxgjfeMFqyP6Q/a1mbNo9m2cWpX2ILaCazF8BMfEgZjyq7zzpybg+EjaLiorNnaeyFt9pUSJdS7AlUuK8K/jnECUcwPRMBvYen2Haj4SOsaLgpi8t+kN0H0XT7aMroStFYFxhbeXxEDkfx+t1fRbQ2lsgbAAA="; }
        }
    }
}
