// <auto-generated />
namespace BasicConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Some : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("BasicConsoleApp.Migrations.add_Some", typeof(add_Some).Assembly);

        string IMigrationMetadata.Id
        {
            get { return "201802020835421_add_Some"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
