// <auto-generated />
namespace BasicConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_BlogSome2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("BasicConsoleApp.Migrations.201802152032477_add_Blog.Some2", typeof(add_BlogSome2).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "201802152032477_add_Blog.Some2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
