// <auto-generated />
namespace BasicConsoleApp.Migrations2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Some : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Some));
        
        string IMigrationMetadata.Id
        {
            get { return "201705040508580_Some"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X227jNhB9L9B/IPjUAlkzl5c2kHbhteMi6DoJVtl9p6WxTZQXlaQC+9v60E/qL3Sou6U4zqZFURgwLHLmzJnDmaH81x9/Rh92SpInsE4YHdOLyTkloFOTCb2JaeHX736iH95//110k6kd+drYXQU79NQuplvv82vGXLoFxd1EidQaZ9Z+khrFeGbY5fn5z+ziggFCUMQiJPpcaC8UlA/4ODM6hdwXXC5NBtLV67iTlKjkjitwOU8hph+5Eyk6OCNhmueTyoOSqRQc2SQg15RwrY3nHrlef3GQeGv0JslxgcvHfQ5ot+bSQZ3DdWf+2nTOL0M6rHNsoNLCeaO+EfDiqtaHDd3fpDJt9UMFb1Bpvw9ZlyrGdGEMJcM41zNpg80xfSfodUYGe2dtQWDdhM8ZmRXSFxZiDYW3XJ6Rh2IlRfor7B/Nb6BjXUjZp4cEce9gAZcerMnB+v1nWNekbzNK2KEfGzq2bj2fKqdb7a8uKbnD4HwloT39Xv6JNxZ+AQ2We8geuPdgdcCAUr9R9EGs8N1Ew3LD7qFkyXefQG/8Nqb4k5KF2EHWrNQMvmiBzYZO3hZwGCRi3dGNDxRPwXOBdGsCU8xkC3a+Chuw888cMXZCfcqujneYUgWcgO8KBfuqI1E116Ssn+eItpS69mVV/zZ9zo40erTkeY6a9Rq/XiFJ1fWzd8m3t4KqMFjqnumIlm0bCSuAb2Cwi6GR6UJY5+fc8xUPpzbL1MhsdABHxG3C9TQeln8neWMcflcOx9tzCNOJuMC8FNZxmSK0TKpRMPIqpy6X3D7TTjMjC6WPteRL3lWD9P2rlTFCxAa0h/KwkT6DwTDU+qVaHZq00duaHdRmVNfJ6ZtqVDiVCSUozZPIQtEke+dBTYLBJPldzqTAfDuDJddiDc5Xs5PiRXE5uOj+P5cOcy6Tp2+e/3z2iyDoyek+uhpeP+71E7fpltsfFN/92Ef6pyN9PHhOzutj47qqvJhmK3x4rOhV4/2Ng3zcBBHrv9RFc3Bi00GEVzwNaaiuDrSxudVr0wiM6fQZNSYD/ZfgeYaqTK0Xa5563E7BufLa/cplgSY3agXZrb4vfF74qXOgVvLgGo/Yy/HL2+qQc3Sfhyf3b6SANAWmAPf6YyFk1vJejOvvGEQokLqokRW+diDcZt8i3Rn9SqBavjnkoENLPILKJYK5e53wJ3gLN3zZ+AQbnu6bWXYc5PRBHMoezQXfWK5cjdH5hz8qLPxTef83oi+R5dsMAAA="; }
        }
    }
}
