// <auto-generated />
namespace BasicConsoleApp.Migrations2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_FooSome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager("BasicConsoleApp.Migrations2.add_FooSome", typeof(add_FooSome).Assembly);
        
        string IMigrationMetadata.Id
        {
            get { return "201802152034142_add_Foo.Some"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
